package com.sborm.example.bean;

import com.sborm.core.annotation.Table;
import org.springframework.stereotype.Component;
import java.util.Date;
import com.sborm.core.BaseEntity;
import java.io.Serializable;
import com.sborm.core.annotation.Database;

/**
 * Entity for table 'test.demo' generated by sborm
 * 
 * @author sborm
 * @date 2014-11-16 00:10:28
 */
@Database("test")
@Table("demo")
@Component
public class Demo extends BaseEntity implements Serializable {

	public static final long serialVersionUID = 2233912281609962999L;

	public static final class Columns {
		public static final String id = "id";
		public static final String name = "name";
		public static final String password = "password";
		public static final String createTime = "createTime";
		public static final String type = "type";
	}

	private Integer id;
	private String name;
	private String password;
	private Date createTime;
	private Integer type;

	public void setId (Integer id) {
		this.id = id;
	}
	public Integer getId () {
		return this.id;
	}
	public void setName (String name) {
		this.name = name;
	}
	public String getName () {
		return this.name;
	}
	public void setPassword (String password) {
		this.password = password;
	}
	public String getPassword () {
		return this.password;
	}
	public void setCreateTime (Date createTime) {
		this.createTime = createTime;
	}
	public Date getCreateTime () {
		return this.createTime;
	}
	public void setType (Integer type) {
		this.type = type;
	}
	public Integer getType () {
		return this.type;
	}
}
